name: Arrangements for Solo Piano
baseurl: solopiano
excerpt_separator: "\n\n\n"

permalink: /:year/:month/:day/:title
plugins:
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
